name = "DemoCards"
uuid = "311a05b2-6137-4a5a-b473-18580a3d38b5"
authors = ["Johnny Chen <johnnychen94@hotmail.com>"]
version = "0.4.11"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Mustache = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
Documenter = "0.22, 0.23, 0.24, 0.25, 0.26, 0.27"
Requires = "1.3"
FileIO = "1"
HTTP = "0.6, 0.7, 0.8, 0.9, 1"
ImageCore = "0.7, 0.8, 0.9"
JSON = "0.20, 0.21"
Literate = "2"
Mustache = "0.5, 1.0"
Suppressor = "0.2"
YAML = "0.3, 0.4"
julia = "1.6"

[extras]
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageShow = "4e3cecfd-b093-5904-9786-8bbb286a6a31"
ReferenceTests = "324d217c-45ce-50fc-942e-d289b448e8cf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestImages = "5e47fb64-e119-507b-a336-dd2b206d9990"

[targets]
test = ["ImageMagick", "ImageShow", "ReferenceTests", "Test", "TestImages"]
